main:
  #- name: "About"
  #  url: "about"
  #  enable: false
  #  weight: 1
  - name: "News"
    url: "https://build.prestashop-project.org"
    weight: 1
  - name: "Download"
    weight: 2
  - name: "Latest Releases"
    parent: "Download"
    url: "https://github.com/PrestaShop/PrestaShop/releases"
    weight: 1
  - name: "Community"
    weight: 3
  - name: "GitHub"
    parent: "Community"
    url: "https://github.com/PrestaShop/PrestaShop/"
    weight: 1
  - name: "Get Involved"
    parent: "Community"
    url: "get-involved"
    weight: 2
  - name: "Contributors"
    parent: "Community"
    url: "https://contributors.prestashop.com/"
    weight: 3
  - name: "Support"
    pageRef: "support"
    weight: 4
  - name: "Resources"
    weight: 5

footer_left:
  - name: Blog
    url: "https://build.prestashop-project.org"
  - name: GitHub
    url: "https://github.com/PrestaShop/PrestaShop/"
  - name: Slack
    pageRef: "slack"

footer_middle:
  - name: "User documentation"
    url: "https://prestashop.gitbook.io/english-documentation-1-7/"
    weight: 1
  - name: "Developer documentation"
    url: "https://devdocs.prestashop-project.org"
    weight: 2
  - name: "Specifications"
    url: "https://build.prestashop-project.org/prestashop-specs/"
    weight: 3

footer_right:
  - name: "Code of conduct"
    pageRef: "code-of-conduct"
    weight: 10
  - name: "Maintainer's guide"
    pageRef: "maintainers-guide"
    weight: 20
  - name: "Legal notice"
    pageRef: "legal"
    weight: 30
